version: '2'

services:
  redis:
    container_name: redis
    image: redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
  rabbitmq:
    container_name: rabbitmq
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_DISK_FREE_LIMIT=1000000000
    depends_on:
      - redis
    volumes:
      - './rabbitmq:/bitnami'
    restart: always
  dispatcher: 
    depends_on:
      - rabbitmq
      - redis
    build: 
      context: ./tracker
      dockerfile: tracker.dockerfile
    volumes:
      - ./tracker:/var/www
    working_dir: /var/www
    command: /bin/sh -c "npm install  && node getinformation.js"
  worker: 
    build: 
      context: ./tracker
      dockerfile: worker.dockerfile
    depends_on:
      - rabbitmq
      - redis
      - dispatcher
    volumes:
      - ./tracker:/var/www
    working_dir: /var/www
    command: /bin/sh -c "node ./utils/worker.js"     
  api:
    build:
      context: ./API
      dockerfile: dev.dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - TWITTER_USER=
      - TWITTER_EMAIL=
      - TWITTER_PASSWORD=
      - NODE_ENV=dev
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./API:/var/www
    working_dir: /var/www
    command: /bin/sh -c "npm install && npm run start"      

