version: '2'

services:
  api:
    build:
      context: ./API
      dockerfile: dev.dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - TWITTER_USER=
      - TWITTER_EMAIL=
      - TWITTER_PASSWORD=
      - MDB_NAME=platzi-store
      - MDB_PORT=27017
      - MDB_HOST=mongo
      - CDB_NAME=platzi_store
      - CDB_PORT=8091
      - CDB_HOST=couchbase
      - CDB_USER=admin
      - CDB_PASSWORD=admin123
      - NODE_ENV=dev
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./API:/var/www
    working_dir: /var/www
    command: /bin/sh -c "npm install && npm run dev"    
  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitMQ:/bitnami'
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../redis/data:/data
    restart: always
volumes:
  rabbitMQ:
    driver: local
